### ISSUE TITLE
Hi,  what does the Rectangle borderRectangle mean?

### ISSUE THREAD

**Issue by donaldlee2008** [surmenok/ImageRecognition#1]
org.surmenok.ml.images.objectDetection.ObjectFinderTrainingImage.ObjectFinderTrainingImage(String fileName, Rectangle[] objectRectangles, Rectangle borderRectangle)

 what does the Rectangle borderRectangle mean?
can you upload the example images?

**Comment by surmenok** [comment]
This property is used only by org.surmenok.ml.images.objectDetection.ObjectFinder which is doing object detection: moving a sliding window over the image and trying to classify each window.
borderRectangle is just a way to reduce search space to some region of the image. For example, if you are searching for eyes on a photo and you happen to know a position of a human face, you can tell the algorithm to search only inside of the rectangle where the face is located.
I can't upload example images because I'm not sure what copyright restrictions there might be.

As a general thought, this is the project I have done 3 years ago when I have little knowledge of computer vision. It is a fully connected neural network and it won't work nearly as well as modern convolutional neural networks. If you want to train a good object detection model, I would suggest to look for things like YOLO9000, Faster R-CNN, Mask R-CNN. Thesel links can be a good start: https://research.fb.com/downloads/detectron/, https://pjreddie.com/darknet/yolo/.

**Comment by donaldlee2008** [comment]
thank you
